#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#include "zlib.h"

// These symbols are generated by ld when converting pg1342.txt into pg1342.o
extern unsigned char _binary_pg1342_txt_start[];
//extern unsigned char _binary_pg1342_txt_end[];
extern unsigned char _binary_pg1342_txt_size[];

int main(void) {
    size_t input_size = (size_t) _binary_pg1342_txt_size;

    printf("INFO: Checking required compress buffer size\n");
    size_t compress_buf_size = compressBound_z(input_size);

    printf("INFO: Allocating compress buffer\n");
    unsigned char *compress_buf = malloc(compress_buf_size);

    printf("INFO: Compressing input data\n");
    int compress_result = compress_z(compress_buf, &compress_buf_size,
                                     _binary_pg1342_txt_start,
                                     input_size);
    if (compress_result != Z_OK) {
        printf("ERROR: zlib compress() call did not return Z_OK\n");
        return 1;
    }

    size_t decompress_buf_size = input_size;

    printf("INFO: Allocating decompress buffer\n");
    unsigned char *decompress_buf = malloc(decompress_buf_size);

    printf("INFO: Decompressing input data\n");
    int decompress_result = uncompress_z(decompress_buf, &decompress_buf_size,
                                         compress_buf, compress_buf_size);
    if (decompress_result != Z_OK) {
        printf("ERROR: zlib uncompress() call did not return Z_OK\n");
        return 1;
    }

    if (decompress_buf_size != input_size) {
        printf("ERROR: zlib uncompress() result is not the same size as the input data\n");
        return 1;
    }

    printf("INFO: Checking decompress result matches the original data\n");
    if (memcmp(_binary_pg1342_txt_start, decompress_buf,
               decompress_buf_size) != 0) {
        printf("ERROR: zlib uncompress() result does not match the original data\n");
        return 1;
    }

    printf("INFO: Success\n");
    free(compress_buf);
    free(decompress_buf);

    return 0;
}
